languageCode = 'en-us'
title = 'Terraform configuration as prose'

theme = "hugo-book"

[params]
  BookRepo = 'https://github.com/staticaland/literate-terraform'

[markup]
  [markup.highlight]
    style = 'tango'
